version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
      - image: circleci/mongo:3.6
    working_directory: ~/laravel
    steps:
      - checkout
      - environment:
          APP_KEY=base64:lxhhUFB1SL6mpIoOurC29CpvQDXKDTjY7dnQTCsISHI=
      - run: echo -e "extension=mongodb.so" | sudo tee /usr/local/etc/php/php.ini > /dev/null
      - run: sudo pecl install -f mongodb-1.4.2
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update
      - run: composer install -n --prefer-dist
      - run: vendor/bin/phpunit
